# Generated by Django 4.2.9 on 2025-06-05 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='studio',
        ),
    ]
