# Generated by Django 5.1.5 on 2025-06-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_question_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='death_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='genre',
            name='killer_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
