# Generated by Django 5.1.5 on 2025-07-03 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_genre_death_name_genre_killer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='killer_name',
            new_name='creature_name',
        ),
    ]
