# Generated by Django 5.1.5 on 2025-10-30 16:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_alter_gameresult_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='button',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
