# Generated by Django 5.1.5 on 2025-10-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_genre_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='chapter_number',
            field=models.IntegerField(null=True),
        ),
    ]
