# Generated by Django 5.1.5 on 2025-11-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
