# Generated by Django 4.2.9 on 2025-05-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile_icon',
            field=models.CharField(choices=[('01', 'icon01'), ('02', 'icon01'), ('03', 'icon01'), ('04', 'icon01'), ('05', 'icon01'), ('06', 'icon01'), ('07', 'icon01')], default='04'),
        ),
    ]
