# Generated by Django 4.2.9 on 2025-05-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userdata_bio_userdata_profile_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='profile_icon',
        ),
        migrations.AddField(
            model_name='userdata',
            name='player_icon',
            field=models.CharField(choices=[('01', 'icon01'), ('02', 'icon02'), ('03', 'icon03'), ('04', 'icon04'), ('05', 'icon05'), ('06', 'icon06'), ('07', 'icon07')], default='04'),
        ),
    ]
