# Generated by Django 5.1.5 on 2025-10-10 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_usericon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_icon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usericon'),
        ),
    ]
