# Generated by Django 5.1.5 on 2025-10-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userdata_user_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usericon',
            name='icon',
            field=models.ImageField(upload_to='icons/'),
        ),
    ]
