# Generated by Django 5.1.5 on 2025-10-10 12:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usericon_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usericon',
            name='icon',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
