# Generated by Django 5.1.5 on 2025-10-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_usericon_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usericon',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
