# Generated by Django 5.1.5 on 2025-11-07 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_genre_description'),
        ('user', '0006_usericon_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='fav_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favourite_1', to='data.film'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='fav_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favourite_2', to='data.film'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='fav_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favourite_3', to='data.film'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='fav_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favourite_4', to='data.film'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='fav_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favourite_5', to='data.film'),
        ),
    ]
